module.exports = function (sequelize, DataTypes) {
  var EndUsers = sequelize.define("EndUsers", {
    name: { type: DataTypes.STRING },
    title: { type: DataTypes.STRING },
    location: { type: DataTypes.STRING },
    itemHist1: { type: DataTypes.STRING },
    itemHist2: { type: DataTypes.STRING },
    itemHist3: { type: DataTypes.STRING },
    itemHist4: { type: DataTypes.STRING },
    itemHist5: { type: DataTypes.STRING },
    itemHist6: { type: DataTypes.STRING },
    itemHist7: { type: DataTypes.STRING },
    itemHist8: { type: DataTypes.STRING },
    itemHist9: { type: DataTypes.STRING },
    itemHist10: { type: DataTypes.STRING },
    itemHist11: { type: DataTypes.STRING },
    itemHist12: { type: DataTypes.STRING },
    itemQuant1: { type: DataTypes.INTEGER },
    itemQuant2: { type: DataTypes.INTEGER },
    itemQuant3: { type: DataTypes.INTEGER },
    itemQuant4: { type: DataTypes.INTEGER },
    itemQuant5: { type: DataTypes.INTEGER },
    itemQuant6: { type: DataTypes.INTEGER },
    itemQuant7: { type: DataTypes.INTEGER },
    itemQuant8: { type: DataTypes.INTEGER },
    itemQuant9: { type: DataTypes.INTEGER },
    itemQuant10: { type: DataTypes.INTEGER },
    itemQuant11: { type: DataTypes.INTEGER },
    itemQuant12: { type: DataTypes.INTEGER },
    itemHist1Date: { type: DataTypes.DATEONLY },
    itemHist2Date: { type: DataTypes.DATEONLY },
    itemHist3Date: { type: DataTypes.DATEONLY },
    itemHist4Date: { type: DataTypes.DATEONLY },
    itemHist5Date: { type: DataTypes.DATEONLY },
    itemHist6Date: { type: DataTypes.DATEONLY },
    itemHist7Date: { type: DataTypes.DATEONLY },
    itemHist8Date: { type: DataTypes.DATEONLY },
    itemHist9Date: { type: DataTypes.DATEONLY },
    itemHist10Date: { type: DataTypes.DATEONLY },
    itemHist11Date: { type: DataTypes.DATEONLY },
    itemHist12Date: { type: DataTypes.DATEONLY },
  });

  return EndUsers;
};
